mutation UpsertEntry(
  $id: String!
  $uid: String!
  $title: String!
  $body: String!
  $entryDateStart: Date!
  $entryDateEnd: Date!
  $eventStartAt: Timestamp
  $eventEndAt: Timestamp
  $originType: String!
  $source: String!
  $status: String!
  $currentRevisionId: String
  $createdAt: Timestamp!
  $updatedAt: Timestamp!
) @auth(level: USER) {
  entry_upsert(data: {
    id: $id
    uid: $uid
    title: $title
    body: $body
    entryDateStart: $entryDateStart
    entryDateEnd: $entryDateEnd
    eventStartAt: $eventStartAt
    eventEndAt: $eventEndAt
    originType: $originType
    source: $source
    status: $status
    currentRevisionId: $currentRevisionId
    createdAt: $createdAt
    updatedAt: $updatedAt
  })
}
